/* eslint-disable no-undef */
const BASE_URL = process.env.REACT_APP_API_BASE_URL
const PATH_LOGIN = "/users/sign_in.json"
const PATH_FACEBOOK_LOGIN = "/auth/mobile/facebook.json"
const PATH_APPLE_LOGIN = "/auth/mobile/apple.json"
const PATH_GOOGLE_LOGIN = "/auth/mobile/google.json"
const PATH_LOGOUT = "/users/sign_out"
// const PATH_SIGNUP = "/users.json"; // not currently needed
const PATH_SIGNUP_FROM_GUEST = "/users/from_guest.json"
const PROFILE = "/profiles" // example: /profiles/<uuid>.json
const PATH_MY_PROFILE = "/profile.json"
const AUTH = "/auth"
const PATH_SUGGEST = "/autocomplete/interests"
const PATH_GUEST = "/users/guest" // -> suggestion '/users'
const PATH_USERS_LIST = "/suggestions.json" // NOTE: let the troll troll
const CHANNEL = "/chat"
const PATH_GROUP_SUGGESTIONS = "/chat/suggestions.json"
const PATH_GROUP_CHAT = "/chat.json"
const PATH_INBOX_MARK_AS_READ = "/inbox/read"
const PATH_UPDATE_AVATAR = "/profile/upload.json"
const PATH_RESET_PASSWORD = "/password/recover"
const PATH_FORGOT_PASSWORD = "/password/lost"
const PATH_PARTNERS_LIST = "/partners"
const PATH_PARTICIPANTS = "/chat_participants"
const PATH_ADD_USER_TO_GROUP = "/chat_suggestions.json"
const PATH_DELETE_CHAT_MESSAGE = "/message"
const PATH_BLACKLIST_USER = "/blacklist"

export const LOGIN = `${BASE_URL}${PATH_LOGIN}`
export const FACEBOOK_LOGIN = `${BASE_URL}${PATH_FACEBOOK_LOGIN}`
export const APPLE_LOGIN = `${BASE_URL}${PATH_APPLE_LOGIN}`
export const GOOGLE_LOGIN = `${BASE_URL}${PATH_GOOGLE_LOGIN}`
export const LOGOUT = `${BASE_URL}${PATH_LOGOUT}`
export const SIGNUP = `${BASE_URL}${PATH_SIGNUP_FROM_GUEST}`
export const SUGGESTION = `${BASE_URL}${PATH_SUGGEST}`
export const GUEST = `${BASE_URL}${PATH_GUEST}`
export const AUTH_USER = `${BASE_URL}${AUTH}`
export const GET_USER_PROFILE = `${BASE_URL}${PROFILE}`
export const USERS_LIST = `${BASE_URL}${PATH_USERS_LIST}`
export const PARTNERS_LIST = `${BASE_URL}${PATH_PARTNERS_LIST}`
export const GROUP_SUGGESTIONS = `${BASE_URL}${PATH_GROUP_SUGGESTIONS}`
export const GROUP_CHAT = `${BASE_URL}${PATH_GROUP_CHAT}`
export const GROUP_CHAT_ADD = "/add.json"
export const GROUP_CHAT_LEAVE = "/remove.json"
export const CHAT_CHANNEL = `${BASE_URL}${CHANNEL}`
export const MY_PROFILE = `${BASE_URL}${PATH_MY_PROFILE}`
export const MARK_CHAT_AS_READ = "/read"
export const MARK_INBOX_AS_READ = `${BASE_URL}${PATH_INBOX_MARK_AS_READ}`
export const WS_ACTIONCABLE = process.env.REACT_APP_WSS_BASE_URL
export const WS_ACTIONCABLE_CHANNEL_PARTNERS_NEW_MESSAGE = "NewMessageChannel"
export const WS_ACTIONCABLE_CHANNEL_SUGGESTIONS = "SuggestionsChannel"
export const UPDATE_AVATAR = `${BASE_URL}${PATH_UPDATE_AVATAR}`
export const RESET_PASSWORD = `${BASE_URL}${PATH_RESET_PASSWORD}`
export const FORGOT_PASSWORD = `${BASE_URL}${PATH_FORGOT_PASSWORD}`
export const CHAT_PARTICIPANTS = `${BASE_URL}${PATH_PARTICIPANTS}`
export const CHAT_MENTION_PERSON = `${BASE_URL}${CHANNEL}`
export const GROUP_ADD_USER = `${BASE_URL}${PATH_ADD_USER_TO_GROUP}`
export const DELETE_CHAT_MESSAGE = `${BASE_URL}${PATH_DELETE_CHAT_MESSAGE}`
export const BLOCK_USER = `${BASE_URL}${PATH_BLACKLIST_USER}`
